version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: ./integration/Postgres.Dockerfile
    restart: always
    ports:
      - 5432:5432
  qradar:
    build:
      context: .
      dockerfile: ./integration/QRadar.Dockerfile
    volumes:
      - .:/count-mvs
    depends_on:
      - "postgres"
    command: python3 /count-mvs/countMVS.py
