version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./integration/api/Dockerfile
    command: python /api/api.py
  postgres:
    build:
      context: .
      dockerfile: ./integration/db/Dockerfile
    restart: always
  py3_integration:
    build:
      context: .
      dockerfile: ./integration/env/Dockerfile
    volumes:
      - .:/count-mvs
      - ./log:/var/log
    depends_on:
      - "postgres"
      - "api"
    command: python3 -m pytest --pyversion 3 ${INTEGRATION_TESTS:-integration/test/}
  py2_integration:
    build:
      context: .
      dockerfile: ./integration/env/Dockerfile
    volumes:
      - .:/count-mvs
      - ./log:/var/log
    depends_on:
      - "postgres"
      - "api"
    command: python3 -m pytest --pyversion 2 ${INTEGRATION_TESTS:-integration/test/}
