name: build
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project into working directory
        uses: actions/checkout@v1
      - name: Build dev Docker image
        run: make docker
      - name: Format code, fail if there are any differences after beautifying
        run: make format && git diff --exit-code
      # Linting currently disabled until linting issues are fixed
      # - run: make lint_local
      - name: Run tests
        run: make test
