name: build
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone project into working directory
        uses: actions/checkout@v1
      - name: Build dev Docker image
        run: make docker
      - name: Format code, fail if there are any differences after beautifying
        run: make format && git diff --exit-code
      - name: Run pylint against code
        run: make lint
      - name: Run tests
        run: make test
      - name: Python 2 SonarCloud
        if: github.event_name != 'release' && github.repository == 'IBM/count-mvs' && github.ref == 'refs/heads/main'
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: python2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PY2 }}
      - name: Python 3 SonarCloud
        if: github.event_name != 'release' && github.repository == 'IBM/count-mvs' && github.ref == 'refs/heads/main'
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: python3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_PY3 }}
